const Map<String, String> countries = {
  'AFG': 'Afghanistan (افغانستان)',
  'ALB': 'Albania (Shqipëria)',
  'DZA': 'Algeria (الجزائر)',
  'ASM': 'American Samoa (Amerika Sāmoa)',
  'AND': 'Andorra (Andorra)',
  'AGO': 'Angola (Angola)',
  'AIA': 'Anguilla (Anguilla)',
  'ATA': 'Antarctica (Antarctica)',
  'ATG': 'Antigua and Barbuda (Antigua and Barbuda)',
  'ARG': 'Argentina (Argentina)',
  'ARM': 'Armenia (Հայաստան)',
  'ABW': 'Aruba (Aruba)',
  'AUS': 'Australia (Australia)',
  'AUT': 'Austria (Österreich)',
  'AZE': 'Azerbaijan (Azərbaycan)',
  'BHS': 'Bahamas (The Bahamas)',
  'BHR': 'Bahrain (البحرين)',
  'BGD': 'Bangladesh (বাংলাদেশ)',
  'BRB': 'Barbados (Barbados)',
  'BLR': 'Belarus (Беларусь)',
  'BEL': 'Belgium (België)',
  'BLZ': 'Belize (Belize)',
  'BEN': 'Benin (Bénin)',
  'BMU': 'Bermuda (Bermuda)',
  'BTN': 'Bhutan (འབྲུག་ཡུལ)',
  'BOL': 'Bolivia (Bolivia)',
  'BIH': 'Bosnia and Herzegovina (Bosna i Hercegovina)',
  'BWA': 'Botswana (Botswana)',
  'BVT': 'Bouvet Island (Bouvetøya)',
  'BRA': 'Brazil (Brasil)',
  'IOT': 'British Indian Ocean Territory (British Indian Ocean Territory)',
  'BRN': 'Brunei Darussalam (Brunei)',
  'BGR': 'Bulgaria (България)',
  'BFA': 'Burkina Faso (Burkina Faso)',
  'BDI': 'Burundi (Burundi)',
  'KHM': 'Cambodia (កម្ពុជា)',
  'CMR': 'Cameroon (Cameroun)',
  'CAN': 'Canada (Canada)',
  'CPV': 'Cape Verde (Cabo Verde)',
  'CYM': 'Cayman Islands (Cayman Islands)',
  'CAF': 'Central African Republic (République centrafricaine)',
  'TCD': 'Chad (Tchad)',
  'CHL': 'Chile (Chile)',
  'CHN': 'China (中国)',
  'CXR': 'Christmas Island (Christmas Island)',
  'CCK': 'Cocos (Keeling) Islands (Cocos (Keeling) Islands)',
  'COL': 'Colombia (Colombia)',
  'COM': 'Comoros (جزر القمر)',
  'COG': 'Congo (Congo)',
  'COD': 'Congo, Democratic Republic (République démocratique du Congo)',
  'COK': 'Cook Islands (Cook Islands)',
  'CRI': 'Costa Rica (Costa Rica)',
  'CIV': 'Côte d\'Ivoire (Côte d\'Ivoire)',
  'HRV': 'Croatia (Hrvatska)',
  'CUB': 'Cuba (Cuba)',
  'CYP': 'Cyprus (Κύπρος)',
  'CZE': 'Czech Republic (Česká republika)',
  'DNK': 'Denmark (Danmark)',
  'DJI': 'Djibouti (Djibouti)',
  'DMA': 'Dominica (Dominica)',
  'DOM': 'Dominican Republic (República Dominicana)',
  'ECU': 'Ecuador (Ecuador)',
  'EGY': 'Egypt (مصر)',
  'SLV': 'El Salvador (El Salvador)',
  'GNQ': 'Equatorial Guinea (Guinea Ecuatorial)',
  'ERI': 'Eritrea (إريتريا)',
  'EST': 'Estonia (Eesti)',
  'ETH': 'Ethiopia (ኢትዮጵያ)',
  'FLK': 'Falkland Islands (Falkland Islands)',
  'FRO': 'Faroe Islands (Føroyar)',
  'FJI': 'Fiji (Fiji)',
  'FIN': 'Finland (Suomi)',
  'FRA': 'France (France)',
  'GUF': 'French Guiana (Guyane française)',
  'PYF': 'French Polynesia (Polynésie française)',
  'ATF': 'French Southern Territories (Terres australes françaises)',
  'GAB': 'Gabon (Gabon)',
  'GMB': 'Gambia (Gambia)',
  'GEO': 'Georgia (საქართველო)',
  'DEU': 'Germany (Deutschland)',
  'GHA': 'Ghana (Ghana)',
  'GIB': 'Gibraltar (Gibraltar)',
  'GRC': 'Greece (Ελλάδα)',
  'GRL': 'Greenland (Kalaallit Nunaat)',
  'GRD': 'Grenada (Grenada)',
  'GLP': 'Guadeloupe (Guadeloupe)',
  'GUM': 'Guam (Guam)',
  'GTM': 'Guatemala (Guatemala)',
  'GGY': 'Guernsey (Guernsey)',
  'GIN': 'Guinea (Guinée)',
  'GNB': 'Guinea-Bissau (Guiné-Bissau)',
  'GUY': 'Guyana (Guyana)',
  'HTI': 'Haiti (Haïti)',
  'HMD': 'Heard Island and McDonald Islands (Heard Island and McDonald Islands)',
  'VAT': 'Holy See (Vaticano)',
  'HND': 'Honduras (Honduras)',
  'HKG': 'Hong Kong (香港)',
  'HUN': 'Hungary (Magyarország)',
  'ISL': 'Iceland (Ísland)',
  'IND': 'India (भारत)',
  'IDN': 'Indonesia (Indonesia)',
  'IRN': 'Iran (ایران)',
  'IRQ': 'Iraq (العراق)',
  'IRL': 'Ireland (Éire)',
  'IMN': 'Isle of Man (Isle of Man)',
  'ISR': 'Israel (ישראל)',
  'ITA': 'Italy (Italia)',
  'JAM': 'Jamaica (Jamaica)',
  'JPN': 'Japan (日本)',
  'JEY': 'Jersey (Jersey)',
  'JOR': 'Jordan (الأردن)',
  'KAZ': 'Kazakhstan (Қазақстан)',
  'KEN': 'Kenya (Kenya)',
  'KIR': 'Kiribati (Kiribati)',
  'KOR': 'Korea, South (대한민국)',
  'KWT': 'Kuwait (الكويت)',
  'KGZ': 'Kyrgyzstan (Кыргызстан)',
  'LAO': 'Laos (ລາວ)',
  'LVA': 'Latvia (Latvija)',
  'LBN': 'Lebanon (لبنان)',
  'LSO': 'Lesotho (Lesotho)',
  'LBR': 'Liberia (Liberia)',
  'LBY': 'Libya (ليبيا)',
  'LIE': 'Liechtenstein (Liechtenstein)',
  'LTU': 'Lithuania (Lietuva)',
  'LUX': 'Luxembourg (Lëtzebuerg)',
  'MAC': 'Macao (澳門)',
  'MKD': 'North Macedonia (Северна Македонија)',
  'MDG': 'Madagascar (Madagascar)',
  'MWI': 'Malawi (Malawi)',
  'MYS': 'Malaysia (Malaysia)',
  'MDV': 'Maldives (ދިވެހިރާއްޖެ)',
  'MLI': 'Mali (Mali)',
  'MLT': 'Malta (Malta)',
  'MHL': 'Marshall Islands (Marshall Islands)',
  'MTQ': 'Martinique (Martinique)',
  'MRT': 'Mauritania (موريتانيا)',
  'MUS': 'Mauritius (Mauritius)',
  'MYT': 'Mayotte (Mayotte)',
  'MEX': 'Mexico (México)',
  'FSM': 'Micronesia (Micronesia)',
  'MDA': 'Moldova (Moldova)',
  'MCO': 'Monaco (Monaco)',
  'MNG': 'Mongolia (Монгол улс)',
  'MNE': 'Montenegro (Crna Gora)',
  'MSR': 'Montserrat (Montserrat)',
  'MAR': 'Morocco (المغرب)',
  'MOZ': 'Mozambique (Moçambique)',
  'MMR': 'Myanmar (မြန်မာ)',
  'NAM': 'Namibia (Namibia)',
  'NRU': 'Nauru (Nauru)',
  'NPL': 'Nepal (नेपाल)',
  'NLD': 'Netherlands (Nederland)',
  'NCL': 'New Caledonia (Nouvelle-Calédonie)',
  'NZL': 'New Zealand (New Zealand)',
  'NIC': 'Nicaragua (Nicaragua)',
  'NER': 'Niger (Niger)',
  'NGA': 'Nigeria (Nigeria)',
  'NIU': 'Niue (Niue)',
  'NFK': 'Norfolk Island (Norfolk Island)',
  'MNP': 'Northern Mariana Islands (Northern Mariana Islands)',
  'NOR': 'Norway (Norge)',
  'OMN': 'Oman (عُمان)',
  'PAK': 'Pakistan (پاکستان)',
  'PLW': 'Palau (Palau)',
  'PSE': 'Palestine (فلسطين)',
  'PAN': 'Panama (Panamá)',
  'PNG': 'Papua New Guinea (Papua New Guinea)',
  'PRY': 'Paraguay (Paraguay)',
  'PER': 'Peru (Perú)',
  'PHL': 'Philippines (Pilipinas)',
  'PCN': 'Pitcairn (Pitcairn)',
  'POL': 'Poland (Polska)',
  'PRT': 'Portugal (Portugal)',
  'PRI': 'Puerto Rico (Puerto Rico)',
  'QAT': 'Qatar (قطر)',
  'REU': 'Réunion (Réunion)',
  'ROU': 'Romania (România)',
  'RUS': 'Russia (Россия)',
  'RWA': 'Rwanda (Rwanda)',
  'BLM': 'Saint Barthélemy (Saint-Barthélemy)',
  'SHN': 'Saint Helena (Saint Helena)',
  'KNA': 'Saint Kitts and Nevis (Saint Kitts and Nevis)',
  'LCA': 'Saint Lucia (Saint Lucia)',
  'MAF': 'Saint Martin (Saint-Martin)',
  'SPM': 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
  'VCT': 'Saint Vincent and the Grenadines (Saint Vincent and the Grenadines)',
  'WSM': 'Samoa (Samoa)',
  'SMR': 'San Marino (San Marino)',
  'STP': 'Sao Tome and Principe (São Tomé e Príncipe)',
  'SAU': 'Saudi Arabia (العربية السعودية)',
  'SEN': 'Senegal (Sénégal)',
  'SRB': 'Serbia (Србија)',
  'SYC': 'Seychelles (Seychelles)',
  'SLE': 'Sierra Leone (Sierra Leone)',
  'SGP': 'Singapore (Singapore)',
  'SVK': 'Slovakia (Slovensko)',
  'SVN': 'Slovenia (Slovenija)',
  'SLB': 'Solomon Islands (Solomon Islands)',
  'SOM': 'Somalia (Soomaaliya)',
  'ZAF': 'South Africa (South Africa)',
  'SGS': 'South Georgia (South Georgia)',
  'ESP': 'Spain (España)',
  'LKA': 'Sri Lanka (ශ්‍රී ලංකාව)',
  'SDN': 'Sudan (السودان)',
  'SUR': 'Suriname (Suriname)',
  'SJM': 'Svalbard and Jan Mayen (Svalbard og Jan Mayen)',
  'SWZ': 'Eswatini (Eswatini)',
  'SWE': 'Sweden (Sverige)',
  'CHE': 'Switzerland (Schweiz)',
  'SYR': 'Syria (سوريا)',
  'TWN': 'Taiwan (台灣)',
  'TJK': 'Tajikistan (Тоҷикистон)',
  'TZA': 'Tanzania (Tanzania)',
  'THA': 'Thailand (ประเทศไทย)',
  'TLS': 'Timor-Leste (Timor-Leste)',
  'TGO': 'Togo (Togo)',
  'TKL': 'Tokelau (Tokelau)',
  'TON': 'Tonga (Tonga)',
  'TTO': 'Trinidad and Tobago (Trinidad and Tobago)',
  'TUN': 'Tunisia (تونس)',
  'TUR': 'Turkey (Türkiye)',
  'TKM': 'Turkmenistan (Türkmenistan)',
  'TCA': 'Turks and Caicos Islands (Turks and Caicos Islands)',
  'TUV': 'Tuvalu (Tuvalu)',
  'UGA': 'Uganda (Uganda)',
  'UKR': 'Ukraine (Україна)',
  'ARE': 'United Arab Emirates (الإمارات العربية المتحدة)',
  'GBR': 'United Kingdom (United Kingdom)',
  'USA': 'United States (United States)',
  'UMI': 'United States Minor Outlying Islands (United States Minor Outlying Islands)',
  'URY': 'Uruguay (Uruguay)',
  'UZB': 'Uzbekistan (Oʻzbekiston)',
  'VUT': 'Vanuatu (Vanuatu)',
  'VEN': 'Venezuela (Venezuela)',
  'VNM': 'Vietnam (Việt Nam)',
  'VGB': 'Virgin Islands, British (Virgin Islands, British)',
  'VIR': 'Virgin Islands, U.S. (Virgin Islands, U.S.)',
  'WLF': 'Wallis and Futuna (Wallis-et-Futuna)',
  'ESH': 'Western Sahara (الصحراء الغربية)',
  'YEM': 'Yemen (اليمن)',
  'ZMB': 'Zambia (Zambia)',
  'ZWE': 'Zimbabwe (Zimbabwe)',
};
